// ── The Notebook — Design System ──────────────────────────────────────────────

export const LIGHT = {
  black:         "#111111",
  offWhite:      "#faf9f7",
  white:         "#ffffff",
  beige:         "#f0ede8",
  border:        "#ebebeb",
  accent:        "#b5522b",
  accentLight:   "#f5ede9",
  accentMid:     "#d4714a",
  textPrimary:   "#111111",
  textSecondary: "#555555",
  textMuted:     "#999999",
  textFaint:     "#bbbbbb",
  publicGreen:   "#1a6b3c",
  publicBg:      "#e6f4ed",
  privateGray:   "#888888",
  privateBg:     "#f2f2f2",
  headerBg:      "#111111",
  headerBorder:  "#ebebeb",
  inputBg:       "#ffffff",
  inputBorder:   "#e0e0e0",
  toolbarBg:     "#f7f7f5",
  toolbarBorder: "#eeeeee",
  toolbarBtn:    "#ffffff",
  toolbarBtnBorder: "#dddddd",
  toolbarBtnText:"#333333",
  sourceBg:      "#f9f9f7",
  cardBg:        "#ffffff",
  cardThumbBg:   "#f0f0f0",
  bodyText:      "#1a1a1a",
  readingTimeBg: "#f5f5f3",
  readingTimeText:"#aaaaaa",
  metaText:      "#aaaaaa",
  linkColor:     "#333333",
  filterBg:      "#ffffff",
  filterBgAlt:   "#fafafa",
  filterBorder:  "#dddddd",
  filterBorderAlt:"#e8e8e8",
  editorBg:      "transparent",
  editorBorder:  "#eeeeee",
  editorBorderStrong: "#e0e0e0",
  summaryColor:  "#666666",
  authorColor:   "#555555",
};

export const DARK = {
  black:         "#ede8e2",
  offWhite:      "#141210",
  white:         "#1e1c1a",
  beige:         "#262320",
  border:        "#333030",
  accent:        "#c96a3c",
  accentLight:   "#2e1a10",
  accentMid:     "#d4724a",
  textPrimary:   "#ede8e2",
  textSecondary: "#a09488",
  textMuted:     "#6e6560",
  textFaint:     "#706860",
  publicGreen:   "#2d9e5f",
  publicBg:      "#0d2e1a",
  privateGray:   "#888888",
  privateBg:     "#2a2826",
  headerBg:      "#0d0c0b",
  headerBorder:  "#2a2826",
  inputBg:       "#262320",
  inputBorder:   "#3a3735",
  toolbarBg:     "#262320",
  toolbarBorder: "#333030",
  toolbarBtn:    "#1e1c1a",
  toolbarBtnBorder: "#3a3735",
  toolbarBtnText:"#c8c0b8",
  sourceBg:      "#262320",
  cardBg:        "#1e1c1a",
  cardThumbBg:   "#2a2826",
  bodyText:      "#d8d0c8",
  readingTimeBg: "#262320",
  readingTimeText:"#6e6560",
  metaText:      "#8a8078",
  linkColor:     "#c8c0b8",
  filterBg:      "#2a2826",
  filterBgAlt:   "#252220",
  filterBorder:  "#3a3735",
  filterBorderAlt:"#333030",
  editorBg:      "transparent",
  editorBorder:  "#333030",
  editorBorderStrong: "#3a3735",
  summaryColor:  "#a09488",
  authorColor:   "#a09488",
};

// Keep legacy THEME export for any future use
export const THEME = {
  color: LIGHT,
  font: {
    serif:  "Georgia, 'Times New Roman', serif",
    sans:   "system-ui, -apple-system, sans-serif",
  },
  space: { xs:4, sm:8, md:16, lg:24, xl:40, xxl:64 },
  radius: { sm:6, md:10, lg:14, pill:999 },
  shadow: {
    card:   "0 1px 4px rgba(0,0,0,.04)",
    hover:  "0 8px 28px rgba(0,0,0,.09)",
    modal:  "0 24px 64px rgba(0,0,0,.2)",
    sidebar:"4px 0 24px rgba(0,0,0,.08)",
  },
};

export const TOPIC_COLORS = {
  "Energy":          "#6b4c1a",
  "Technology":      "#1a3a6b",
  "Markets":         "#1a6b3c",
  "Consumer Trends": "#4c1a6b",
  "Environment":     "#2d6b1a",
  "Deep Dive":       "#111111",
  "Other":           "#555555",
};

// Lightened versions for dark backgrounds
export const DARK_TOPIC_COLORS = {
  "Energy":          "#c48a3a",
  "Technology":      "#4a7ec4",
  "Markets":         "#3aab6b",
  "Consumer Trends": "#9a5ac4",
  "Environment":     "#5aab3a",
  "Deep Dive":       "#c8c0b8",
  "Other":           "#a09488",
};

export const REGION_COLORS = {
  "Africa":       "#b45309",
  "Americas":     "#0369a1",
  "Asia-Pacific": "#7c3aed",
  "Europe":       "#0f766e",
  "Middle East":  "#b91c1c",
  "Global":       "#6b7280",
};

export const TRANSLATIONS = {
  en: {
    // Nav / Sidebar
    siteTitle:       "The Notebook",
    adminSection:    "Admin",
    publicationSection: "Publication",
    newArticle:      "New Article",
    logout:          "Logout",
    login:           "Login",
    about:           "About",
    contact:         "Contact",
    // About panel
    aboutHeading:    "About The Notebook",
    aboutP1:         "The Notebook is an independent analysis publication. We write about the forces shaping economies, industries, and markets : from the energy transition to the technology shifts transforming the world as we know it.",
    aboutP2:         "Through latest research, expert insight, data, and the news, cross-referenced against what matters most: the people driving these changes and those living them. We deliver a straightforward analysis to educate ourselves, and share it plainly.",
    // Contact panel
    contactHeading:  "Get in touch",
    contactSent:     "✓ Message sent — thank you!",
    fieldName:       "Name",
    fieldEmail:      "Email",
    fieldSubject:    "Subject",
    fieldMessage:    "Message",
    placeholderName: "Your name",
    placeholderEmail:"your@email.com",
    placeholderSubject:"What's this about?",
    placeholderMessage:"Your message…",
    sendMessage:     "Send Message",
    // Footer
    footerTagline:   "Independent analysis publication",
    footerCopy:      "Franz-Frederick Acclassato · All rights reserved",
    footerDisclaimer:"Published content is for informational and educational purposes, powered by the drive to discover and explain.",
    // Login modal
    adminLogin:      "Admin Login",
    loginSubtext:    "Private articles are password protected",
    enterPassword:   "Enter password",
    incorrectPassword:"Incorrect password",
    connectionError: "Connection error",
    checking:        "Checking…",
    cancel:          "Cancel",
    // Filter bar
    searchPlaceholder:"Search articles…",
    filterAll:       "All",
    filterPublic:    "Public",
    filterPrivate:   "Private",
    filterTopic:     "Topic",
    filterRegion:    "Region",
    // Editor
    back:            "Back",
    save:            "Save",
    saved:           "✓ Saved",
    statusPublic:    "Public",
    statusPrivate:   "Private",
    labelTopics:     "Topics",
    labelRegion:     "Region",
    labelBody:       "Body",
    labelSources:    "Sources & References",
    placeholderTitle:"Article title…",
    placeholderSummary:"One-sentence summary / lede…",
    placeholderAuthor:"Author name…",
    placeholderSourceName:"Source name",
    placeholderSourceUrl:"https://...",
    addSource:       "Add",
    // Reader
    by:              "By",
    lastRevised:     "Last revised",
    deleteConfirm:   "Delete this article?",
    // Empty state
    comingSoon:      "New articles coming soon!",
    loading:         "Loading…",
    minRead:         "min read",
    edit:            "Edit",
    locale:          "en-US",
    topicLabels: {
      "Energy":"Energy","Technology":"Technology","Markets":"Markets",
      "Consumer Trends":"Consumer Trends","Environment":"Environment",
      "Deep Dive":"Deep Dive","Other":"Other",
    },
    regionLabels: {
      "Africa":"Africa","Americas":"Americas","Asia-Pacific":"Asia-Pacific",
      "Europe":"Europe","Middle East":"Middle East","Global":"Global",
    },
  },
  fr: {
    siteTitle:       "The Notebook",
    adminSection:    "Admin",
    publicationSection: "Publication",
    newArticle:      "Nouvel article",
    logout:          "Déconnexion",
    login:           "Connexion",
    about:           "À propos",
    contact:         "Contact",
    aboutHeading:    "À propos de The Notebook",
    aboutP1:         "The Notebook est une publication d'analyse indépendante. Nous écrivons sur les forces qui façonnent les économies, les industries et les marchés : de la transition énergétique aux mutations technologiques qui transforment notre monde.",
    aboutP2:         "À travers les dernières recherches, des analyses d'experts, des données et l'actualité, croisées avec ce qui compte le plus : les personnes qui conduisent ces changements et celles qui les vivent. Nous livrons une analyse directe pour nous instruire et la partageons simplement.",
    contactHeading:  "Nous contacter",
    contactSent:     "✓ Message envoyé — merci !",
    fieldName:       "Nom",
    fieldEmail:      "E-mail",
    fieldSubject:    "Sujet",
    fieldMessage:    "Message",
    placeholderName: "Votre nom",
    placeholderEmail:"votre@email.com",
    placeholderSubject:"De quoi s'agit-il ?",
    placeholderMessage:"Votre message…",
    sendMessage:     "Envoyer",
    footerTagline:   "Publication d'analyse indépendante",
    footerCopy:      "Franz-Frederick Acclassato · Tous droits réservés",
    footerDisclaimer:"Le contenu publié est à titre informatif et éducatif.",
    adminLogin:      "Connexion Admin",
    loginSubtext:    "Les articles privés sont protégés par mot de passe",
    enterPassword:   "Entrez le mot de passe",
    incorrectPassword:"Mot de passe incorrect",
    connectionError: "Erreur de connexion",
    checking:        "Vérification…",
    cancel:          "Annuler",
    searchPlaceholder:"Rechercher des articles…",
    filterAll:       "Tous",
    filterPublic:    "Public",
    filterPrivate:   "Privé",
    filterTopic:     "Thème",
    filterRegion:    "Région",
    back:            "Retour",
    save:            "Enregistrer",
    saved:           "✓ Enregistré",
    statusPublic:    "Public",
    statusPrivate:   "Privé",
    labelTopics:     "Thèmes",
    labelRegion:     "Région",
    labelBody:       "Corps",
    labelSources:    "Sources et références",
    placeholderTitle:"Titre de l'article…",
    placeholderSummary:"Résumé en une phrase…",
    placeholderAuthor:"Nom de l'auteur…",
    placeholderSourceName:"Nom de la source",
    placeholderSourceUrl:"https://...",
    addSource:       "Ajouter",
    by:              "Par",
    lastRevised:     "Dernière révision",
    deleteConfirm:   "Supprimer cet article ?",
    comingSoon:      "De nouveaux articles arrivent bientôt !",
    loading:         "Chargement…",
    minRead:         "min de lecture",
    edit:            "Modifier",
    locale:          "fr-FR",
    topicLabels: {
      "Energy":"Énergie","Technology":"Technologie","Markets":"Marchés",
      "Consumer Trends":"Tendances","Environment":"Environnement",
      "Deep Dive":"Analyse","Other":"Autre",
    },
    regionLabels: {
      "Africa":"Afrique","Americas":"Amériques","Asia-Pacific":"Asie-Pacifique",
      "Europe":"Europe","Middle East":"Moyen-Orient","Global":"Mondial",
    },
  },
  es: {
    siteTitle:       "The Notebook",
    adminSection:    "Admin",
    publicationSection: "Publicación",
    newArticle:      "Nuevo artículo",
    logout:          "Cerrar sesión",
    login:           "Iniciar sesión",
    about:           "Acerca de",
    contact:         "Contacto",
    aboutHeading:    "Acerca de The Notebook",
    aboutP1:         "The Notebook es una publicación de análisis independiente. Escribimos sobre las fuerzas que dan forma a las economías, industrias y mercados: desde la transición energética hasta los cambios tecnológicos que transforman el mundo.",
    aboutP2:         "A través de investigaciones recientes, análisis de expertos, datos y noticias, contrastados con lo que más importa: las personas que impulsan estos cambios y quienes los viven. Ofrecemos un análisis directo para educarnos y lo compartimos con claridad.",
    contactHeading:  "Contáctenos",
    contactSent:     "✓ Mensaje enviado — ¡gracias!",
    fieldName:       "Nombre",
    fieldEmail:      "Correo",
    fieldSubject:    "Asunto",
    fieldMessage:    "Mensaje",
    placeholderName: "Tu nombre",
    placeholderEmail:"tu@correo.com",
    placeholderSubject:"¿De qué se trata?",
    placeholderMessage:"Tu mensaje…",
    sendMessage:     "Enviar mensaje",
    footerTagline:   "Publicación de análisis independiente",
    footerCopy:      "Franz-Frederick Acclassato · Todos los derechos reservados",
    footerDisclaimer:"El contenido publicado es de carácter informativo y educativo.",
    adminLogin:      "Acceso Admin",
    loginSubtext:    "Los artículos privados están protegidos por contraseña",
    enterPassword:   "Introduce la contraseña",
    incorrectPassword:"Contraseña incorrecta",
    connectionError: "Error de conexión",
    checking:        "Verificando…",
    cancel:          "Cancelar",
    searchPlaceholder:"Buscar artículos…",
    filterAll:       "Todos",
    filterPublic:    "Público",
    filterPrivate:   "Privado",
    filterTopic:     "Tema",
    filterRegion:    "Región",
    back:            "Volver",
    save:            "Guardar",
    saved:           "✓ Guardado",
    statusPublic:    "Público",
    statusPrivate:   "Privado",
    labelTopics:     "Temas",
    labelRegion:     "Región",
    labelBody:       "Cuerpo",
    labelSources:    "Fuentes y referencias",
    placeholderTitle:"Título del artículo…",
    placeholderSummary:"Resumen en una frase…",
    placeholderAuthor:"Nombre del autor…",
    placeholderSourceName:"Nombre de la fuente",
    placeholderSourceUrl:"https://...",
    addSource:       "Añadir",
    by:              "Por",
    lastRevised:     "Última revisión",
    deleteConfirm:   "¿Eliminar este artículo?",
    comingSoon:      "¡Próximamente nuevos artículos!",
    loading:         "Cargando…",
    minRead:         "min de lectura",
    edit:            "Editar",
    locale:          "es-ES",
    topicLabels: {
      "Energy":"Energía","Technology":"Tecnología","Markets":"Mercados",
      "Consumer Trends":"Tendencias","Environment":"Medio ambiente",
      "Deep Dive":"Análisis","Other":"Otro",
    },
    regionLabels: {
      "Africa":"África","Americas":"Américas","Asia-Pacific":"Asia-Pacífico",
      "Europe":"Europa","Middle East":"Oriente Medio","Global":"Global",
    },
  },
  de: {
    siteTitle:       "The Notebook",
    adminSection:    "Admin",
    publicationSection: "Publikation",
    newArticle:      "Neuer Artikel",
    logout:          "Abmelden",
    login:           "Anmelden",
    about:           "Über uns",
    contact:         "Kontakt",
    aboutHeading:    "Über The Notebook",
    aboutP1:         "The Notebook ist eine unabhängige Analysepublikation. Wir schreiben über die Kräfte, die Volkswirtschaften, Industrien und Märkte prägen: von der Energiewende bis zu den technologischen Veränderungen, die unsere Welt transformieren.",
    aboutP2:         "Durch aktuelle Forschung, Experteneinblicke, Daten und Nachrichten – abgeglichen mit dem, was am meisten zählt: die Menschen, die diese Veränderungen antreiben, und jene, die sie erleben. Wir liefern klare Analysen zur eigenen Bildung und teilen sie offen.",
    contactHeading:  "Kontakt aufnehmen",
    contactSent:     "✓ Nachricht gesendet — danke!",
    fieldName:       "Name",
    fieldEmail:      "E-Mail",
    fieldSubject:    "Betreff",
    fieldMessage:    "Nachricht",
    placeholderName: "Ihr Name",
    placeholderEmail:"ihre@email.de",
    placeholderSubject:"Worum geht es?",
    placeholderMessage:"Ihre Nachricht…",
    sendMessage:     "Nachricht senden",
    footerTagline:   "Unabhängige Analysepublikation",
    footerCopy:      "Franz-Frederick Acclassato · Alle Rechte vorbehalten",
    footerDisclaimer:"Die veröffentlichten Inhalte dienen Informations- und Bildungszwecken.",
    adminLogin:      "Admin-Anmeldung",
    loginSubtext:    "Private Artikel sind passwortgeschützt",
    enterPassword:   "Passwort eingeben",
    incorrectPassword:"Falsches Passwort",
    connectionError: "Verbindungsfehler",
    checking:        "Überprüfe…",
    cancel:          "Abbrechen",
    searchPlaceholder:"Artikel suchen…",
    filterAll:       "Alle",
    filterPublic:    "Öffentlich",
    filterPrivate:   "Privat",
    filterTopic:     "Thema",
    filterRegion:    "Region",
    back:            "Zurück",
    save:            "Speichern",
    saved:           "✓ Gespeichert",
    statusPublic:    "Öffentlich",
    statusPrivate:   "Privat",
    labelTopics:     "Themen",
    labelRegion:     "Region",
    labelBody:       "Inhalt",
    labelSources:    "Quellen & Referenzen",
    placeholderTitle:"Artikeltitel…",
    placeholderSummary:"Zusammenfassung in einem Satz…",
    placeholderAuthor:"Autorenname…",
    placeholderSourceName:"Quellenname",
    placeholderSourceUrl:"https://...",
    addSource:       "Hinzufügen",
    by:              "Von",
    lastRevised:     "Zuletzt überarbeitet",
    deleteConfirm:   "Diesen Artikel löschen?",
    comingSoon:      "Neue Artikel kommen bald!",
    loading:         "Laden…",
    minRead:         "Min. Lesezeit",
    edit:            "Bearbeiten",
    locale:          "de-DE",
    topicLabels: {
      "Energy":"Energie","Technology":"Technologie","Markets":"Märkte",
      "Consumer Trends":"Verbrauchertrends","Environment":"Umwelt",
      "Deep Dive":"Analyse","Other":"Sonstiges",
    },
    regionLabels: {
      "Africa":"Afrika","Americas":"Amerika","Asia-Pacific":"Asien-Pazifik",
      "Europe":"Europa","Middle East":"Naher Osten","Global":"Global",
    },
  },
};
